language: android

jdk:
  - oraclejdk7

env:
  global:
    - NDK_VER=r9d
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-8 ANDROID_ABI=armeabi

android:
  components:
    - build-tools-19.1.0
    - android-17
    - android-8
  licenses:
    - android-sdk-license-[0-9a-f]{8}

install:
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-${NDK_VER}-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-${NDK_VER}-linux-x86.tar.bz2 -O ndk.tgz; fi
  - tar -xf ndk.tgz
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-${NDK_VER}

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew assembleDebug

notifications:
  slack:
    secure: E+LzDFiEM+Hx6gbPbcDD7pOZyhStEVZ3K8/isKY8ZllMaDEPXS9so9z5PWJLUNsmXmJY06/RvVOiTsJFu6wlYi9r08VZA9Ygaq6JKky9chlyrHBdai44nNJj4EBtsvtWib1o4IRgJJAtfsUYNxtpKKHO/PvAONNPp22lIXoVOpE=
